# Generated by Django 3.1.4 on 2020-12-15 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('article_id', models.UUIDField()),
                ('vote', models.IntegerField(choices=[(1, 'UP'), (2, 'DOWN')])),
            ],
            options={
                'unique_together': {('user_id', 'article_id')},
                'db_table': 'article_vote'
            },
        ),
    ]
