name: Static analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: "Install Dependencies"
        run: pip install -r requirements.txt

      - name: "Run static analysis"
        run: make static-analysis
